# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_rst_ps7_0_50M_1/system_axo_axi_rst_ps7_0_50M_1.xci
# IP: The module: 'system_axo_axi_rst_ps7_0_50M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_rst_ps7_0_50M_1/system_axo_axi_rst_ps7_0_50M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axo_axi_rst_ps7_0_50M_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_rst_ps7_0_50M_1/system_axo_axi_rst_ps7_0_50M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axo_axi_rst_ps7_0_50M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_rst_ps7_0_50M_1/system_axo_axi_rst_ps7_0_50M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axo_axi_rst_ps7_0_50M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: H:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_rst_ps7_0_50M_1/system_axo_axi_rst_ps7_0_50M_1.xci
# IP: The module: 'system_axo_axi_rst_ps7_0_50M_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_rst_ps7_0_50M_1/system_axo_axi_rst_ps7_0_50M_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axo_axi_rst_ps7_0_50M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_rst_ps7_0_50M_1/system_axo_axi_rst_ps7_0_50M_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axo_axi_rst_ps7_0_50M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_rst_ps7_0_50M_1/system_axo_axi_rst_ps7_0_50M_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axo_axi_rst_ps7_0_50M_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
