# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: H:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/system_axo_axi_axi_smc_1.xci
# IP: The module: 'system_axo_axi_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/bd_470a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_10/bd_470a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_16/bd_470a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_23/bd_470a_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_29/bd_470a_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_24/bd_470a_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_25/bd_470a_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_26/bd_470a_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_27/bd_470a_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_28/bd_470a_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_22/bd_470a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_17/bd_470a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_18/bd_470a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_19/bd_470a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_20/bd_470a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_21/bd_470a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_11/bd_470a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_12/bd_470a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_13/bd_470a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_14/bd_470a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_15/bd_470a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_7/bd_470a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_8/bd_470a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_9/bd_470a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_2/bd_470a_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_3/bd_470a_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_4/bd_470a_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_5/bd_470a_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_6/bd_470a_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_0/bd_470a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_1/bd_470a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_10/bd_470a_s00a2s_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_16/bd_470a_m00s2a_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_23/bd_470a_m01s2a_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_24/bd_470a_m01arn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_25/bd_470a_m01rn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_26/bd_470a_m01awn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_27/bd_470a_m01wn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_28/bd_470a_m01bn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_17/bd_470a_m00arn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_18/bd_470a_m00rn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_19/bd_470a_m00awn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_20/bd_470a_m00wn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_21/bd_470a_m00bn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_11/bd_470a_sarn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_12/bd_470a_srn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_13/bd_470a_sawn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_14/bd_470a_swn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_15/bd_470a_sbn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_2/bd_470a_arsw_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_3/bd_470a_rsw_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_4/bd_470a_awsw_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_5/bd_470a_wsw_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_6/bd_470a_bsw_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_1/bd_470a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_1/bd_470a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axo_axi_axi_smc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: H:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/system_axo_axi_axi_smc_1.xci
# IP: The module: 'system_axo_axi_axi_smc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/bd_470a.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_10/bd_470a_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_16/bd_470a_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_23/bd_470a_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_29/bd_470a_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_24/bd_470a_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_25/bd_470a_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_26/bd_470a_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_27/bd_470a_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_28/bd_470a_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_22/bd_470a_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_17/bd_470a_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_18/bd_470a_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_19/bd_470a_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_20/bd_470a_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_21/bd_470a_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_11/bd_470a_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_12/bd_470a_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_13/bd_470a_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_14/bd_470a_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_15/bd_470a_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_7/bd_470a_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_8/bd_470a_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_9/bd_470a_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_2/bd_470a_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_3/bd_470a_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_4/bd_470a_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_5/bd_470a_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_6/bd_470a_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_0/bd_470a_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_1/bd_470a_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_10/bd_470a_s00a2s_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_16/bd_470a_m00s2a_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_23/bd_470a_m01s2a_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_24/bd_470a_m01arn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_25/bd_470a_m01rn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_26/bd_470a_m01awn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_27/bd_470a_m01wn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_28/bd_470a_m01bn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_17/bd_470a_m00arn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_18/bd_470a_m00rn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_19/bd_470a_m00awn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_20/bd_470a_m00wn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_21/bd_470a_m00bn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_11/bd_470a_sarn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_12/bd_470a_srn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_13/bd_470a_sawn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_14/bd_470a_swn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_15/bd_470a_sbn_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_2/bd_470a_arsw_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_3/bd_470a_rsw_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_4/bd_470a_awsw_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_5/bd_470a_wsw_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_6/bd_470a_bsw_0_ooc.xdc

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_1/bd_470a_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_1/bd_470a_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axo_axi_axi_smc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
