# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/system_axo_axi/system_axo_axi.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axo_axi || ORIG_REF_NAME==system_axo_axi} -quiet] -quiet

# IP: bd/system_axo_axi/ip/system_axo_axi_processing_system7_0_0/system_axo_axi_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axo_axi_processing_system7_0_0 || ORIG_REF_NAME==system_axo_axi_processing_system7_0_0} -quiet] -quiet

# IP: bd/system_axo_axi/ip/system_axo_axi_axi_bram_ctrl_0_0/system_axo_axi_axi_bram_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axo_axi_axi_bram_ctrl_0_0 || ORIG_REF_NAME==system_axo_axi_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/system_axo_axi/ip/system_axo_axi_axi_bram_ctrl_0_bram_2/system_axo_axi_axi_bram_ctrl_0_bram_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axo_axi_axi_bram_ctrl_0_bram_2 || ORIG_REF_NAME==system_axo_axi_axi_bram_ctrl_0_bram_2} -quiet] -quiet

# IP: bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/system_axo_axi_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axo_axi_axi_smc_1 || ORIG_REF_NAME==system_axo_axi_axi_smc_1} -quiet] -quiet

# IP: bd/system_axo_axi/ip/system_axo_axi_rst_ps7_0_50M_1/system_axo_axi_rst_ps7_0_50M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axo_axi_rst_ps7_0_50M_1 || ORIG_REF_NAME==system_axo_axi_rst_ps7_0_50M_1} -quiet] -quiet

# IP: bd/system_axo_axi/ip/system_axo_axi_ANDXOR_0_0/system_axo_axi_ANDXOR_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==system_axo_axi_ANDXOR_0_0 || ORIG_REF_NAME==system_axo_axi_ANDXOR_0_0} -quiet] -quiet

# XDC: bd/system_axo_axi/system_axo_axi_ooc.xdc
