# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir H:/dev/CSASA/bch_fpga_2/bch_fpga_2.cache/wt [current_project]
set_property parent.project_path H:/dev/CSASA/bch_fpga_2/bch_fpga_2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths h:/dev/CSASA/ip/ANDXOR_1.0 [current_project]
set_property ip_output_repo h:/dev/CSASA/bch_fpga_2/bch_fpga_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib H:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/hdl/system_axo_axi_wrapper.v
add_files H:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/system_axo_axi.bd
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_processing_system7_0_0/system_axo_axi_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_bram_ctrl_0_0/system_axo_axi_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_bram_ctrl_0_bram_2/system_axo_axi_axi_bram_ctrl_0_bram_2_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_10/bd_470a_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_16/bd_470a_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_23/bd_470a_m01s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_24/bd_470a_m01arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_25/bd_470a_m01rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_26/bd_470a_m01awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_27/bd_470a_m01wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_28/bd_470a_m01bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_17/bd_470a_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_18/bd_470a_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_19/bd_470a_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_20/bd_470a_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_21/bd_470a_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_11/bd_470a_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_12/bd_470a_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_13/bd_470a_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_14/bd_470a_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_15/bd_470a_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_2/bd_470a_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_3/bd_470a_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_4/bd_470a_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_5/bd_470a_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_6/bd_470a_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_1/bd_470a_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/bd_0/ip/ip_1/bd_470a_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_axi_smc_1/ooc.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_rst_ps7_0_50M_1/system_axo_axi_rst_ps7_0_50M_1_board.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_rst_ps7_0_50M_1/system_axo_axi_rst_ps7_0_50M_1.xdc]
set_property used_in_implementation false [get_files -all h:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/ip/system_axo_axi_rst_ps7_0_50M_1/system_axo_axi_rst_ps7_0_50M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all H:/dev/CSASA/bch_fpga_2/bch_fpga_2.srcs/sources_1/bd/system_axo_axi/system_axo_axi_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top system_axo_axi_wrapper -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef system_axo_axi_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file system_axo_axi_wrapper_utilization_synth.rpt -pb System_wrapper_utilization_synth.pb"
