webtalk_init -webtalk_dir H:\\dev\\CSASA\\bch_fpga_2\\bch_fpga_2.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-04-26 20:37:17" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dp32lf7i55fdmpre62geekafqu" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.3_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3408 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.276 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1524788555813" -context "sdk\\\\application/1524788555813"
webtalk_add_data -client sdk -key hwid -value "1518138163746" -context "sdk\\\\application/1524788555813"
webtalk_add_data -client sdk -key bspid -value "1518137766690" -context "sdk\\\\application/1524788555813"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1524788555813"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1524788555813"
webtalk_add_data -client sdk -key apptemplate -value "empty_application" -context "sdk\\\\application/1524788555813"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1524788555813"
webtalk_add_data -client sdk -key LangUsed -value "CPP" -context "sdk\\\\application/1524788555813"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1524788555813"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1524793037770"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1524793037770"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1524793037770"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1524793037770"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1524793037770"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1524793037770"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1524793037770"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1524793037770"
webtalk_transmit -clientid 2662438882 -regid "" -xml H:\\dev\\CSASA\\bch_fpga_2\\bch_fpga_2.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html H:\\dev\\CSASA\\bch_fpga_2\\bch_fpga_2.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm H:\\dev\\CSASA\\bch_fpga_2\\bch_fpga_2.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
